### ISSUE TITLE
xbuild fails

### ISSUE THREAD

**Issue by rsxdalv** [yole/unhood#5]
Output:

```
/home/roberts/Desktop/unhood/UnHood.sln:  warning : Project file /home/roberts/Desktop/unhood/UnHood/UnHood.csproj referenced in the solution file, not found. Ignoring.
Project "/home/roberts/Desktop/unhood/UnHood.sln" (default target(s)):
        Target ValidateSolutionConfiguration:
                Building solution configuration "Debug|Any CPU".
        Target Build:
/home/roberts/Desktop/unhood/UnHood.sln: error : Could not find the project file '/home/roberts/Desktop/unhood/UnHood/UnHood.csproj'
                Project "/home/roberts/Desktop/unhood/UnHood.Engine/UnHood.Engine.csproj" (default target(s)):
                        Target PrepareForBuild:
                                Configuration: Debug Platform: AnyCPU
                        Target GenerateSatelliteAssemblies:
                        No input files were specified for target GenerateSatelliteAssemblies, skipping.
                        Target CoreCompile:
                                Tool /usr/lib/mono/4.5/mcs.exe execution started with arguments: /noconfig /debug:full /debug+ /optimize- /out:obj/Debug/UnHood.Engine.dll BytecodeReader.cs Decompilable.cs FlagSet.cs StatementList.cs StatementListBuilder.cs TextBuilder.cs UE3/ChunkedStream.cs UE3/UE3ClassPropertyReader.cs UE3/UE3ClassReader.cs UE3/UE3ConstReader.cs UE3/UE3EnumReader.cs UE3/UE3PackageReader.cs UE3/UE3FunctionReader.cs UE3/UE3PropertyListReader.cs UE3/UE3ScriptStructReader.cs UE3/UE3StateReader.cs UnClass.cs UnClassProperty.cs UnConst.cs UnEnum.cs UnExport.cs UnFunction.cs UnImport.cs ProblemRegistry.cs UnName.cs UnPackage.cs Properties/AssemblyInfo.cs UnPackageItem.cs UnPropertyList.cs UnScriptStruct.cs UnState.cs /target:library /define:"DEBUG;TRACE" /nostdlib /reference:../References/MiniLZO.dll /reference:/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll /reference:/usr/lib/mono/gac/System.Drawing/4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll /reference:/usr/lib/mono/gac/System.Xml.Linq/4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll /reference:/usr/lib/mono/gac/System.Data.DataSetExtensions/4.0.0.0__b77a5c561934e089/System.Data.DataSetExtensions.dll /reference:/usr/lib/mono/gac/System.Data/4.0.0.0__b77a5c561934e089/System.Data.dll /reference:/usr/lib/mono/gac/System.Xml/4.0.0.0__b77a5c561934e089/System.Xml.dll /reference:/usr/lib/mono/gac/System.Core/4.0.0.0__b77a5c561934e089/System.Core.dll /warn:4
CSC: error CS0518: The predefined type `System.Object' is not defined or imported
CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported
CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported
CSC: error CS0518: The predefined type `System.Int32' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt32' is not defined or imported
CSC: error CS0518: The predefined type `System.Int64' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt64' is not defined or imported
CSC: error CS0518: The predefined type `System.Single' is not defined or imported
CSC: error CS0518: The predefined type `System.Double' is not defined or imported
CSC: error CS0518: The predefined type `System.Char' is not defined or imported
CSC: error CS0518: The predefined type `System.Int16' is not defined or imported
CSC: error CS0518: The predefined type `System.Decimal' is not defined or imported
CSC: error CS0518: The predefined type `System.Boolean' is not defined or imported
CSC: error CS0518: The predefined type `System.SByte' is not defined or imported
CSC: error CS0518: The predefined type `System.Byte' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt16' is not defined or imported
CSC: error CS0518: The predefined type `System.String' is not defined or imported
CSC: error CS0518: The predefined type `System.Enum' is not defined or imported
CSC: error CS0518: The predefined type `System.Delegate' is not defined or imported
CSC: error CS0518: The predefined type `System.MulticastDelegate' is not defined or imported
CSC: error CS0518: The predefined type `System.Void' is not defined or imported
CSC: error CS0518: The predefined type `System.Array' is not defined or imported
CSC: error CS0518: The predefined type `System.Type' is not defined or imported
CSC: error CS0518: The predefined type `System.Collections.IEnumerator' is not defined or imported
CSC: error CS0518: The predefined type `System.Collections.IEnumerable' is not defined or imported
CSC: error CS0518: The predefined type `System.IDisposable' is not defined or imported
CSC: error CS0518: The predefined type `System.IntPtr' is not defined or imported
CSC: error CS0518: The predefined type `System.UIntPtr' is not defined or imported
CSC: error CS0518: The predefined type `System.RuntimeFieldHandle' is not defined or imported
CSC: error CS0518: The predefined type `System.RuntimeTypeHandle' is not defined or imported
CSC: error CS0518: The predefined type `System.Exception' is not defined or imported
                        Task "Csc" execution -- FAILED
                        Done building target "CoreCompile" in project "/home/roberts/Desktop/unhood/UnHood.Engine/UnHood.Engine.csproj".-- FAILED
                Done building project "/home/roberts/Desktop/unhood/UnHood.Engine/UnHood.Engine.csproj".-- FAILED
        Task "MSBuild" execution -- FAILED
        Done building target "Build" in project "/home/roberts/Desktop/unhood/UnHood.sln".-- FAILED
Done building project "/home/roberts/Desktop/unhood/UnHood.sln".-- FAILED

Build FAILED.

Warnings:

/home/roberts/Desktop/unhood/UnHood.sln:  warning : Project file /home/roberts/Desktop/unhood/UnHood/UnHood.csproj referenced in the solution file, not found. Ignoring.

Errors:

/home/roberts/Desktop/unhood/UnHood.sln (default targets) ->
(Build target) ->

        /home/roberts/Desktop/unhood/UnHood.sln: error : Could not find the project file '/home/roberts/Desktop/unhood/UnHood/UnHood.csproj'

/home/roberts/Desktop/unhood/UnHood.sln (default targets) ->
(Build target) ->
/home/roberts/Desktop/unhood/UnHood.Engine/UnHood.Engine.csproj (default targets) ->
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

        CSC: error CS0518: The predefined type `System.Object' is not defined or imported
        CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported
        CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported
        CSC: error CS0518: The predefined type `System.Int32' is not defined or imported
        CSC: error CS0518: The predefined type `System.UInt32' is not defined or imported
        CSC: error CS0518: The predefined type `System.Int64' is not defined or imported
        CSC: error CS0518: The predefined type `System.UInt64' is not defined or imported
        CSC: error CS0518: The predefined type `System.Single' is not defined or imported
        CSC: error CS0518: The predefined type `System.Double' is not defined or imported
        CSC: error CS0518: The predefined type `System.Char' is not defined or imported
        CSC: error CS0518: The predefined type `System.Int16' is not defined or imported
        CSC: error CS0518: The predefined type `System.Decimal' is not defined or imported
        CSC: error CS0518: The predefined type `System.Boolean' is not defined or imported
        CSC: error CS0518: The predefined type `System.SByte' is not defined or imported
        CSC: error CS0518: The predefined type `System.Byte' is not defined or imported
        CSC: error CS0518: The predefined type `System.UInt16' is not defined or imported
        CSC: error CS0518: The predefined type `System.String' is not defined or imported
        CSC: error CS0518: The predefined type `System.Enum' is not defined or imported
        CSC: error CS0518: The predefined type `System.Delegate' is not defined or imported
        CSC: error CS0518: The predefined type `System.MulticastDelegate' is not defined or imported
        CSC: error CS0518: The predefined type `System.Void' is not defined or imported
        CSC: error CS0518: The predefined type `System.Array' is not defined or imported
        CSC: error CS0518: The predefined type `System.Type' is not defined or imported
        CSC: error CS0518: The predefined type `System.Collections.IEnumerator' is not defined or imported
        CSC: error CS0518: The predefined type `System.Collections.IEnumerable' is not defined or imported
        CSC: error CS0518: The predefined type `System.IDisposable' is not defined or imported
        CSC: error CS0518: The predefined type `System.IntPtr' is not defined or imported
        CSC: error CS0518: The predefined type `System.UIntPtr' is not defined or imported
        CSC: error CS0518: The predefined type `System.RuntimeFieldHandle' is not defined or imported
        CSC: error CS0518: The predefined type `System.RuntimeTypeHandle' is not defined or imported
        CSC: error CS0518: The predefined type `System.Exception' is not defined or imported

         1 Warning(s)
         32 Error(s)

Time Elapsed 00:00:00.5756940
```
